Repository skuschel/postpic, pull requests merged in 2018-10, with the labels that each got.

#182 Field._map_coordinates: make shallow copy of newaxes list
  postpic/datahandling.py
Labels: Hacktoberfest, bug, core

#181 Ab/plotter improvements
  postpic/plotting/plotter_matplotlib.py
Labels: Hacktoberfest, plotting

#177 allow reversed axis
  CHANGELOG.md
  postpic/datahandling.py
  postpic/datareader/__init__.py
  postpic/helper.py
  test/test_datahandling.py
Labels: core, enhancement

#179 Axis: Added monotonicity check
  postpic/datahandling.py
  postpic/helper.py
Labels: Hacktoberfest, core

#178 misc
  .travis.yml
  postpic/particles/particles.py
  test/test_particles.py
Labels: Hacktoberfest, core, documentation
