Repository skuschel/postpic, pull requests merged in 2018-03, with the labels that each got.

#171 documentation updates
  .github/issue_template.md
  .gitignore
  CONTRIBUTING.md
  README.md
  doc/source/apidoc/postpic.io.rst
  doc/source/apidoc/postpic.rst
  doc/source/conf.py
  doc/source/introduction.rst
  postpic/__init__.py
  postpic/datahandling.py
Labels: documentation

#170 Some new features
  CHANGELOG.md
  postpic/datahandling.py
  postpic/helper.py
  postpic/plotting/plotter_matplotlib.py
  test/test_datahandling.py
Labels: enhancement

#172 WIP: Field: added method to load image files
  CHANGELOG.md
  postpic/datahandling.py
  postpic/io/__init__.py
  postpic/io/csv.py
  postpic/io/image.py
  postpic/plotting/plotter_matplotlib.py
  setup.py
Labels: enhancement, io
