Repository skuschel/postpic, pull requests merged in 2019-10, with the labels that each got.

#240 Fix helper.jac_det for 1d case
  postpic/datahandling.py
  postpic/helper.py
  test/test_helper.py
Labels: Field, bug

#242 Updated image reader logic to fix #241
  postpic/io/image.py
Labels: bug, io

#245 add Fbpic reader
  CHANGELOG.md
  postpic/_field_calc.py
  postpic/datahandling.py
  postpic/datareader/__init__.py
  postpic/datareader/datareader.py
  postpic/datareader/openPMDh5.py
  postpic/helper.py
Labels: Hacktoberfest, enhancement, reader specific

#248 bugfix fbpicreader
  postpic/_field_calc.py
Labels: bug, reader specific
