Repository skuschel/postpic, pull requests merged in 2019-07, with the labels that each got.

#224 Fix travis CI
  .travis.yml
Labels: testing

#225 Changed return type of `Field._normalize_slices`
  postpic/datahandling.py
  postpic/helper.py
Labels: Field, housekeeping / code cleanup

#226 Pull abc's from collections.abc instead collections
  postpic/_compat/functions.py
  postpic/datahandling.py
  postpic/datareader/datareader.py
  postpic/particles/_routines.py
  postpic/particles/scalarproperties.py
Labels: housekeeping / code cleanup

#228 Fix calls to numpy.?stack methods
  postpic/io/vtk.py
  postpic/particles/particles.py
Labels: housekeeping / code cleanup

#230 Ab/fix 221
  CHANGELOG.md
  postpic/datahandling.py
  test/test_datahandling.py
Labels: Field, incompatible change
