Repository skuschel/postpic, pull requests merged in 2024-07, with the labels that each got.

#281 compatibility to new numpy scipy and numexpr versions
  .github/workflows/run-tests.yml
  postpic/datahandling.py
  postpic/datareader/dummy.py
  postpic/helper.py
  test/test_datahandling.py
Labels: housekeeping / code cleanup, compatibility

#282 bugfix and changelog update
  CHANGELOG.md
  postpic/particles/scalarproperties.py
  setup.py
Labels: bug, housekeeping / code cleanup

#284 add timesteps to datareader
  postpic/datareader/datareader.py
Labels: enhancement
